FROM jupyter/datascience-notebook

USER root

RUN apt-get update && \
    apt-get install -y python3-dev gcc libxml2-dev libxslt-dev musl-dev

WORKDIR /home/jovyan/work

COPY requirements.txt .
RUN echo ' \n\
********** \n\
***** Installing lxml takes too long, I know. I am sorry.. \n\
********** \n\
' && \
pip install -r requirements.txt

# instead of copying, bind dirs when running
# COPY . .
