version: "3.7"

networks:
  python_template_network:

volumes:
  python_template_redis_volume:
  python_template_postgres_volume:

services:

  python_template_web:
    image: ${IMAGE}
    container_name: python_template_web
    build:
      context: .
      dockerfile: Dockerfile${FROM_PREPACK}
      args:
        - PREPACK_IMAGE=${PREPACK_IMAGE}
        - PIP_PARAMS=${PIP_PARAMS}
        - APPUSER=${APPUSER}
    env_file:
      - etc/env/${ENV_NAME}.env
      - ${SECRETS_FILE}
    environment:
      - DO_SETUP
      - ENTRYPOINT_MODE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    ports:
      - ${WEB_PORT}:5000
    networks:
      - python_template_network
    volumes:
      - type: bind
        source: .
        target: /home/${APPUSER}/app

  python_template_redis:
    image: redis:5.0.7-alpine
    container_name: python_template_redis
    command: redis-server
    ports:
      - ${REDIS_PORT_ON_HOST}:6379
    networks:
      - python_template_network
    volumes:
          - python_template_redis_volume:/data

  python_template_postgres:
    image: postgres:12.1-alpine
    container_name: python_template_postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - ${POSTGRES_PORT_ON_HOST}:5432
    networks:
      - python_template_network
    volumes:
      - python_template_postgres_volume:/var/lib/postgresql/data:cached
      - type: bind
        source: .
        target: /mnt/backups

  python_template_jupyter:
    build:
      context: .
      dockerfile: Dockerfile_jupyter
    container_name: python_template_jupyter
    image: python_template_jupyter
    ports:
      - ${JUPYTER_PORT}:8888
    networks:
      - python_template_network
    volumes:
      - ./:/home/jovyan/work
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - DJANGO_ALLOW_ASYNC_UNSAFE
    env_file:
      - etc/env/${ENV_NAME}.env
      - ${SECRETS_FILE}
    depends_on:
      - python_template_redis
      - python_template_postgres

  python_template_nginx:
      image: nginx:1.17.10
      container_name: python_template_nginx
      ports:
        - ${NGINX_PORT_ON_HOST}:${NGINX_PORT}
      networks:
        - python_template_network
      volumes:
        - ./static_web:/usr/share/nginx/html
        - ./etc/nginx/${ENV_NAME}/conf.d/:/etc/nginx/conf.d/
      env_file:
        - etc/env/${ENV_NAME}.env
        - ${SECRETS_FILE}
